[package]
name = "openslide"
version = "0.1.0"
authors = ["Ole-Johan Skrede <ojskrede@gmail.com>"]

[dependencies]
libc = "0.2"
failure = "0.1"
image = "0.19"
num = "0.2"

[build-dependencies]
cc = "1.0"
